### ISSUE TITLE
Issues while setting up the Lab

### ISSUE THREAD

**Issue by RahulIngenious** [iknowjason/Awesome-CloudSec-Labs#2]
Hi Jason,

First of thank you for your fantastic work. I was going through your AwesomeCloudLab -->>
PurpleCloud Azure AD Workshop | Azure | Self-hosted, guided vulnerability workshop | Jason Ostrom | Guided vulnerability workshop requires PurpleCloud and terraform; 

Under this Lab when i am trying to setup. I am getting stuck at step 3 (Return to your Slingshot Linux VM. In a working shell, change into the PurpleCloud directory by typing cd tools/PurpleCloud or cd ~/tools/PurpleCloud.). when i am running the command in my Azure Ubuntu VM to change into PurpleCloud directory i am getting error. No such file or directory. I believe which would be obvious. Could you please help me rectify this issue. so that i could proceed with further steps.

**Comment by iknowjason** [comment]
Hey @RahulIngenious 

The instructions were meant for a Virtual Machine that already had PurpleCloud downloaded.  In your Azure Ubuntu VM first download Purple Cloud using git client.  Then change into the directory.  Here it is, something like this:
```
git clone https://github.com/iknowjason/PurpleCloud.git
```
